config/routes.rb
Rails.application.routes.draw do
  get 'mypage', to: 'users#me'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :users, only: %i[new create]
  resources :boards
  resources :comments, only: %i[create destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  body       :text(65535)
#  name       :string(255)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Board < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :board_tag_relations, dependent: :delete_all
  has_many :tags, through: :board_tag_relations
  validates :name, presence: true, length: {maximum: 10}
  validates :title, presence: true, length: {maximum: 30}
  validates :body, presence: true, length: {maximum:1000}
end

app/models/board_tag_relation.rb
# == Schema Information
#
# Table name: board_tag_relations
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer
#  tag_id     :integer
#
# Indexes
#
#  index_board_tag_relations_on_board_id  (board_id)
#  index_board_tag_relations_on_tag_id    (tag_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#  fk_rails_...  (tag_id => tags.id)
#
class BoardTagRelation < ApplicationRecord
  belongs_to :board
  belongs_to :tag
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  comment    :text(65535)      not null
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer
#
# Indexes
#
#  index_comments_on_board_id  (board_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#
class Comment < ApplicationRecord
  belongs_to :board

  validates :name, presence:true, length: { maximum: 10}
  validates :comment, presence:true, length: {maximum: 1000}
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tag < ApplicationRecord
    has_many :board_tag_relations, dependent: :delete_all
    has_many :boards, through: :board_tag_relations
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_name  (name) UNIQUE
#
class User < ApplicationRecord
    has_secure_password

    validates :name,
      presence: true,
      uniqueness: true,
      length: { maximum: 16 },
      format: {
        with: /\A[a-z0-9]+\z/,
        message: 'は小文字英数字で入力してください'
      }
    validates :password,
      length: { minimum: 8 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
private

def current_user
  return unless session[:user_id]
  @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_target_board, only: %i[show edit update destroy]

  def index
    @boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    @boards = @boards.page(params[:page])
  end

  def new
    @board = Board.new
  end

  def create
    board = Board.new(board_params)
    if board.save
      flash[:notice] = "「#{board.title}」の掲示板を作成しました"
      redirect_to board
    else
      redirect_to new_board_path, flash: {
        board: board,
        error_messages: board.errors.full_messages
      }
    end
  end

  def show
    @comment = Comment.new(board_id: @board.id)
  end

  def edit
  end

  def update
    if @board.update(board_params)
        flash[:notice] = "適切に更新が正行われました"
      redirect_to @board
    else
      redirect_to :back, flash:{
        board: @board,
        error_messages: @board.errors.full_messages
      }
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path,flash: { notice:"「#{@board.title}」の掲示板が削除されました"}
  end


  private

  def board_params
    params.require(:board).permit(:name,:title,:body,tag_ids:[])
  end
  def set_target_board
    @board = Board.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:notice] = 'コメントを投稿しました'
      redirect_to comment.board
    else
      redirect_to :back, flash:{
        comment: comment,
        error_messages: comment.errors.full_messages
      }
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.delete
    redirect_to comment.board, flash: {notice: 'コメントが削除されました'}
  end

  private

  def comment_params
    params.require(:comment).permit(:board_id, :name, :comment)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to mypage_path
    else
      render 'home/index'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new(flash[:user])
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id 
      redirect_to mypage_path
    else
      redirect_to :back, flash: {
        user: user,
        error_messages: user.errors.full_messages
      }
    end
  end

  def me
  end

  private

  def user_params
    params.require(:user).permit(:name,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def header_link_item(name, path)
        class_name = 'nav-item'
        class_name << ' active' if current_page?(path)

        content_tag :li, class: class_name do
            link_to name, path, class: 'nav-link'
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light border-bottom

">
  <a class="navbar-brand" href="#"><%= image_tag 'abo02.png' %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= header_link_item('近くのお店を探す', root_path) %>
      </li>
      <li class="nav-item">
        <%= header_link_item('ロカボ掲示板', boards_path) %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ユーザー管理
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if @current_user %>
            <%= link_to 'マイページ', mypage_path, class: 'dropdown-item' %>
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
          <% else %>
            <%= link_to '登録', new_user_path, class: 'dropdown-item' %>
            <%= link_to 'ログイン', root_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
    
  </div>
</nav>

app/views/boards/_board.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= board.title %></h4>
    <% board.tags.each do |tag| %>
      <span class="badge badge-primary"><%= tag.name %></span>
    <% end %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(board.body) %></p>
    <p class="text-right font-weight-bold mr-10"><%= board.name %></p>
  </div>
</div>

app/views/boards/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_for board do |f| %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>
  <div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板編集</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class:'btn btn-outline-dark' %>
  </div>
</div>
<%= render partial: 'form' ,locals:{ board:@board }%>

app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板一覧</h1>
  <div class="ml-auto boards__linkBox">
    <%= form_tag boards_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み',
                       class: 'form-control boards__select',
                       onchange: 'submit(this.form);'
                     }
      %>
    <% end %>
    <a href="/boards/new" class="btn btn-outline-dark">新規作成</a>
  </div>
</div>

<% if flash[:notice] %>
  <div class="alert alert-danger"><%= flash[:notice] %></div>
<% end %>

<table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.id %></td>
        <td><%= board.title %></td>
        <td><%= board.name %></td>
        <td><%= board.created_at.to_s(:datetime_jp) %></td>
        <td><%= board.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to '詳細', board, class: 'btn btn-outline-dark' %></td>
        <td><%= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @boards %>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧', boards_path, class:'btn btn-outline-dark' %>
  </div>
</div>
<%= render partial: 'form' ,locals:{ board:@board }%>

app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%= link_to '一覧',boards_path,class:'btn btn-outline-dark'%>
    <%= link_to '編集',edit_board_path(@board),class:'btn btn-outline-dark'%>
  </div>
</div>

<% if flash[:notice]%>
  <div class="alert alert-primary"><%= flash[:notice] %>
  </div>
<%end%>

<%= render @board %>

<div class="p-comment__list">
  <div class="p-comment_listTitle">コメント</div>
  <%= render @board.comments %>
</div>

<%#_comment_form.htmlをパーシャルとして流用する%>
<%= render partial: 'comments/form', locals:{ comment: @comment }%>

app/views/comments/_comment.html.erb
<div class="p-comment__item">
  <p><%= simple_format(comment.comment) %></p>
  <div class="p-comment__bottomLine">
    <span><%= comment.name %></span>
    <span><%= comment.created_at.to_s(:datetime_jp) %></span>
    <span><%= link_to '削除', comment, method: :delete, data:{ confirm: '削除してもよろしいですか？'}%></span>
  </div>
</div>

app/views/comments/_form.html.erb
<%= render 'shared/error_messages'%>
<div class="p-comment__formBox">
  <p class="p-comment__formTitle">コメント記入</p>
  <%= form_for comment do |f| %>
    <%= f.hidden_field :board_id %>
    <div class="form-group">
      <%= f.label :name, '名前' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :comment, 'コメント' %>
      <%= f.text_area :comment, class: 'form-control', rows: 4 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/home/index.html.erb
<%= render partial: 'users/search' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Avocabo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    
  </head>

  <body>
  <%= render 'header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if flash[:error_messages]%>
  <div class="alert akert-danger">
    <ul>
      <% flash[:error_messages].each do |msg| %>
        <li><%= msg %></li>
      <%end%>
    </ul>
  </div>
<%end%>

app/views/users/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_for user do |f| %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit '作成', class: 'btn btn-primary' %>
<% end %>

app/views/users/_search.html.erb
    <div id="content">
      <h2>糖質制限ができそうなお店</h2>
      <div id="map" class="map"></div>
      <ul id="shop-list"></ul>
      <a id="serch-button">近くのお店をしらべる</a>

    </div>
    <div class="what-avocabo">
      <a id="a"><h3>AVOCABOとは？</h3></a>
      <%= image_tag 'avocado-cut.png',size: "120x70"%>
      <p>「医者が教える食事術」のベストセラーをはじめ、適度な糖質制限の重要性の関心が高まっているなかで、外食においても「糖質制限」というキーワードでお店選びをされる方が多くなっていると思います。そんな食事に気をつかう方々が効率的に適度な糖質制限ライフを送っていただけるよう、お店検索サイトを作成いたしました。</p>
    </div>

    <div class="to-top">
      <a href="#"><p>PAGE TOP</p></a>
    </div>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4utc0nSonoVSrT_RBWIM7DtRATXrjZoc&callback=initMap"></script>
<script>

var map;

function initMap() {
  map = new google.maps.Map(document.getElementById('map'), {
    zoom: 15,
  });
}


document.getElementById("serch-button").onclick = function() {

let a = navigator.geolocation.getCurrentPosition(test2);
function test2(position) {
  var lat = position.coords.latitude;
  var lng = position.coords.longitude;
  var myPosi = new google.maps.LatLng(lat, lng);
  var marker = new google.maps.Marker({
      position: myPosi,
      map: map,
      icon: {
        url: 'Octocat.png',
        scaledSize: new google.maps.Size(40, 40)
      }
  });

  $.ajax({
    type : "get",
    url　: "https://api.gnavi.co.jp/RestSearchAPI/v3/?keyid=87f9561026d0fabde41ab8b7066fbdd5&freeword=糖質制限,低糖質,ロカボ,ローカーボ,糖質オフ,糖質OFF,糖質ゼロ,グルテンフリー,焼肉,焼き鳥&freeword_condition=2&latitude="+lat+"&longitude="+lng+"&range=4",
    dataType : 'json',
    success　: function(json){
      let num_shop = json.rest.length;
      for( let i=0; i < num_shop; i++){
        console.log(json.rest[i].url);
        var latLng = new google.maps.LatLng(json.rest[i].latitude, json.rest[i].longitude);
        var marker = new google.maps.Marker({
            position: latLng,
            map: map,
            label: {
              text: String(i+1),
              color: "#fff",
              fontWeight: 'bold',
              fontSize: '14px'
            },
            url: json.rest[i].url,
        });
        google.maps.event.addListener(marker, 'click', (function(url){
          return function(){ location.href = url; };
        })(json.rest[i].url));
        $('<li class="each-shop"><i class="fas fa-map-marker fa-3x"></i><span class="icon">'+ String(i+1) + '</span><a href="' + json.rest[i].url + '"><img class="shop-img" src=' + json.rest[i].image_url.shop_image1 + '><span class="shop-content"><span class="shop-name">' + String(i+1) + " " + json.rest[i].name + '</span><span class="time">営業時間：' + json.rest[i].opentime + '</span></span></a></li>').appendTo('#shop-list');
      }
    },
    error: function(json){
      console.log("error")
    }
  });

  var styleOptions = [
    {
      "featureType": "administrative",
      "elementType": "all",
      "stylers": [
        {
          "visibility": "on"
        },
        {
          "lightness": 33
        }
      ]
    },
    {
      "featureType": "landscape",
      "elementType": "all",
      "stylers": [
        {
          "color": "#f2e5d4"
        }
      ]
    },
    {
      "featureType": "poi.park",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#c5dac6"
        }
      ]
    },
    {
        "featureType": "poi.park",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "on"
            },
            {
                "lightness": 20
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
            {
                "lightness": 20
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#c5c6c6"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#e4d7c6"
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#fbfaf7"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            },
            {
                "color": "#acbcc9"
            }
        ]
    }
  ];
  var sampleType = new google.maps.StyledMapType(styleOptions);
  map.mapTypes.set('map', sampleType);
  map.setMapTypeId('map');
  map.setCenter(myPosi);
};
};

</script>

app/views/users/me.html.erb
<h1>マイページ</h1>
<%= @current_user.name %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<%= render partial: 'form', locals: { user: @user } %>